System:
  LOCAL : False
Agent:
  MAX_TOKEN : 0.5
  MODEL : 
Memory:
  CHUNK_SIZE : 2000
  OVERLAP : 500
Status:
  loss_mood_study : 10
  loss_energy_study : 10
  loss_mood_taking_courses : 10
  loss_energy_taking_courses : 10
  loss_energy_socializing : 20
  add_mood_socializing : 10
  add_mood_relax : 50
  add_energy_sleep : 50
  add_energy_exercise : 50
