System:
  DAYS : 56 # 8 Weeks
  PDF_PATH : "textbook.pdf"
  LOG_PATH : "./logs/{date_time}"
Agent:
  LOCAL : False
  MAX_TOKEN : 2000
  STUDENT_MODEL : "gpt-4o-mini"
  TEACHER_MODEL : "gpt-4o"
  LOCAL_MODEL : "llama3.1"
  TEMPERATURE : 1
Memory:
  LOCAL : False
  CHUNK_SIZE : 500
  OVERLAP : 100
  EMBED : "" #OpenAIEmbeddings
  LOCAL_EMBED : "nomic-embed-text"
  FORGET_FACTOR : 0.9
Status:
  loss_mood_study : 10
  loss_energy_study : 10
  loss_mood_take_courses : 10
  loss_energy_take_courses : 10
  loss_energy_socialize : 20
  add_mood_socialize : 10
  add_mood_relax : 50
  add_energy_sleep : 50
  add_health_exercise : 50
