System:
  DAYS : 56 # 8 Weeks
  PDF_PATH : 
Agent:
  LOCAL : False
  MAX_TOKEN : 0.5
  MODEL : "gpt-4o-mini"
  LOCAL_MODEL: "llama3.1:8b"
Memory:
  LOCAL : False
  CHUNK_SIZE : 2000
  OVERLAP : 200
  EMBED : "" #OpenAIEmbeddings
  LOCAL_EMBED : nomic-embed-text
Status:
  loss_mood_study : 10
  loss_energy_study : 10
  loss_mood_taking_courses : 10
  loss_energy_taking_courses : 10
  loss_energy_socializing : 20
  add_mood_socializing : 10
  add_mood_relax : 50
  add_energy_sleep : 50
  add_energy_exercise : 50
